import {test} from 'node:test';
import assert from 'node:assert/strict';
import {passwordHash} from '../server.js';
import {testApp} from '../test-support/database.js';

test('fluxo completo, isolamento de acesso e integridade da chamada',async t=>{
 const {server,db}=await testApp(t);
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 
 const base=`http://127.0.0.1:${server.address().port}/api`;
 function client(){let cookie='',csrf='';return async(path,method='GET',body,expected=200)=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':csrf},...(body?{body:JSON.stringify(body)}:{})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const data=(r.headers.get('content-type')||'').includes('json')?await r.json():await r.arrayBuffer();assert.equal(r.status,expected,JSON.stringify(data));if(data.csrf)csrf=data.csrf;return data;};}
 const teacher=client(),student=client(),outsider=client(),anon=client();
 await anon('/classes','GET',null,401);
 await teacher('/login','POST',{email:'professor@demo.local',password:'Demo@2026!'});await teacher('/me');
 assert.equal((await teacher('/students')).length,10);
 const {id:classId}=await teacher('/classes','POST',{name:'Turma de integração'},201);
 const c=(await teacher('/classes')).find(c=>c.id===classId);
 await anon('/invite?code='+c.invite);
 const registration={invite:c.invite,name:'Aluno Integração',email:'integracao@example.com',password:'SenhaTeste123!',terms:true,phone:'11987654321'};
 await anon('/register','POST',registration,201);
 await anon('/register','POST',registration,400);
 await student('/login','POST',{email:registration.email,password:registration.password});
 let sm=await student('/me');assert.equal(sm.student.status,'pending');
 await student(`/students/${sm.student.id}/qr`,'GET',null,403);
 await student('/classes','GET',null,403);
 await student('/students/1/qr','GET',null,403);
 await teacher(`/students/${sm.student.id}`,'PATCH',{status:'approved'});
 sm=await student('/me');assert.equal(sm.student.status,'approved');assert.equal(sm.student.qr_token,undefined);const qrToken=(await db.get('SELECT qr_token FROM students WHERE id=?',sm.student.id)).qr_token;assert.ok(qrToken);
 const png=await student(`/students/${sm.student.id}/qr`);assert.equal(new Uint8Array(png)[0],137);
 const {id:callId}=await teacher('/calls','POST',{class_id:classId,date:'2026-09-05'},201);
 assert.equal((await teacher('/calls','POST',{class_id:classId,date:'2026-09-05'})).id,callId);
 await student(`/calls/${callId}/scan`,'POST',{token:qrToken},403);
 await teacher(`/calls/${callId}/scan`,'POST',{token:'invalido'},400);
 const otherToken=(await db.get('SELECT qr_token FROM students WHERE id=1')).qr_token;
 await teacher(`/calls/${callId}/scan`,'POST',{token:otherToken},400);
 await teacher(`/calls/${callId}/scan`,'POST',{token:'PRESENCA:'+qrToken});
 await teacher(`/calls/${callId}/scan`,'POST',{token:qrToken},409);
 await teacher(`/calls/${callId}/attendance`,'PATCH',{student_id:sm.student.id,mass:'yes'});
 await teacher(`/calls/${callId}/close`,'POST',{confirm:false},400);
 await teacher(`/calls/${callId}/close`,'POST',{confirm:true});
 await teacher(`/calls/${callId}/scan`,'POST',{token:qrToken},400);
 let report=await teacher(`/report?class_id=${classId}&month=2026-09`);
 assert.equal(report.rows[0].percent,100);assert.equal(report.rows[0].yes,1);
 await teacher(`/calls/${callId}/attendance`,'PATCH',{student_id:sm.student.id,presence:'absent',mass:'no'});
 report=await teacher(`/report?class_id=${classId}&month=2026-09`);assert.equal(report.rows[0].absent,1);
 const logs=await teacher('/logs');assert.ok(logs.some(l=>l.action==='correct'&&l.before_data.includes('present')&&l.after_data.includes('absent')));
 await teacher(`/students/${sm.student.id}/rotate`,'POST');const newSm=await student('/me');assert.equal(newSm.student.qr_token,undefined);assert.notEqual((await db.get('SELECT qr_token FROM students WHERE id=?',sm.student.id)).qr_token,qrToken);
 const next=await teacher('/calls','POST',{class_id:classId,date:'2026-09-04'},201);
 await teacher(`/calls/${next.id}/scan`,'POST',{token:qrToken},400);
 await teacher(`/classes/${classId}`,'PATCH',{mass_present_only:true});
 await teacher(`/calls/${next.id}/attendance`,'PATCH',{student_id:sm.student.id,mass:'yes'},400);
 await teacher(`/calls/${next.id}/close`,'POST',{confirm:true});
 assert.equal((await teacher(`/calls/${next.id}`)).rows[0].presence,'absent');
 await student('/corrections','POST',{message:'Por favor corrija meu nome.'},201);
 assert.equal((await teacher('/corrections')).length,1);
 await db.run("INSERT INTO users(name,email,password,role,created_at) VALUES(?,?,?,'teacher',?)",'Outro professor','outro@example.com',passwordHash('OutraSenha123!'),new Date().toISOString());
 await outsider('/login','POST',{email:'outro@example.com',password:'OutraSenha123!'});await outsider('/me');
 assert.deepEqual(await outsider('/classes'),[]);
 await outsider(`/calls/${callId}`,'GET',null,404);
 await outsider(`/students/${sm.student.id}`,'PATCH',{status:'rejected',reason:'Teste'},404);
 await outsider(`/report?class_id=${classId}&month=2026-09`,'GET',null,404);
 await teacher(`/classes/${classId}`,'PATCH',{renew:true});await anon('/invite?code='+c.invite,'GET',null,404);
 await teacher(`/students/${sm.student.id}`,'PATCH',{active:false});
 await student(`/students/${sm.student.id}/qr`,'GET',null,403);
 assert.equal((await teacher(`/report?class_id=${classId}&month=2026-09`)).rows.length,0);
 assert.equal((await teacher(`/calls/${callId}`)).rows.length,1);
 await teacher('/logout','POST');await teacher('/classes','GET',null,401);
});
