import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {testApp} from '../test-support/database.js';

test('QR: presença imediata, opções de missa, repetição, falha e revisão final',async t=>{
 const {server,db}=await testApp(t);
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base=`http://127.0.0.1:${server.address().port}`;
 const dom=new JSDOM(readFileSync(new URL('../public/index.html',import.meta.url),'utf8'),{url:base,runScripts:'outside-only'});
 t.after(()=>dom.window.close());
 const w=dom.window,$=s=>w.document.querySelector(s);let cookie='',failMass=false,decode,scans=0;
 w.fetch=async(url,options={})=>{
  if(url.endsWith('/scan'))scans++;
  if(failMass&&options.method==='PATCH'&&url.endsWith('/attendance'))return {ok:false,status:503,json:async()=>({error:'Falha de conexão simulada.'})};
  const r=await fetch(base+url,{...options,headers:{...options.headers,Cookie:cookie}});
  if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;
 };
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
 w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.confirm=()=>true;Object.defineProperty(w,'isSecureContext',{value:true});
 w.ZXingBrowser={BrowserQRCodeReader:class{async decodeFromVideoDevice(device,video,callback){decode=callback;return {stop(){}};}}};
 w.eval(readFileSync(new URL('../public/app.js',import.meta.url),'utf8'));
 async function until(fn){for(let i=0;i<1000;i++){if(await fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('Estado esperado não encontrado: '+w.document.body.textContent);}
 await until(()=>$('#login'));
 $('[name=email]').value='professor@demo.local';$('[name=password]').value='Demo@2026!';
 $('#login').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:$('#login button')}));
 await until(()=>$('h1')?.textContent.includes('Olá'));
 w.location.hash='call';await until(()=>$('#start-call'));
 $('#start-call [name=date]').value='2026-09-05';
 $('#start-call').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:$('#start-call button')}));
 await until(()=>$('#video'));
 const call=await db.get("SELECT id FROM calls WHERE date=?",'2026-09-05');
 const students=await db.all('SELECT id,name,qr_token FROM students WHERE id<=4 ORDER BY id');
 const attendance=id=>db.get('SELECT * FROM attendance WHERE call_id=? AND student_id=?',call.id,id);
 $('[data-action=camera]').click();await until(()=>decode);
 let clock=Date.now();w.Date.now=()=>clock;
 async function scan(index){clock+=4000;await decode({getText:()=>`PRESENCA:${students[index].qr_token}`});}
 await scan(0);
 assert.equal((await attendance(1)).presence,'present');
 assert.ok($('#scan-result').textContent.includes(students[0].name+' — Presença registrada'));
 assert.equal($('#mass-question').textContent,'Foi à missa?');
 assert.equal($('#video').parentElement.hidden,true);
 const before=scans;await scan(1);assert.equal(scans,before);
 $('[data-action="scan-mass:yes"]').click();await until(()=>!$('#scan-question'));
 assert.equal((await attendance(1)).mass,'yes');assert.equal($('#video').parentElement.hidden,false);
 await scan(1);$('[data-action="scan-mass:no"]').click();await until(()=>!$('#scan-question'));
 assert.equal((await attendance(2)).mass,'no');
 await scan(2);$('[data-action="scan-mass:unknown"]').click();await until(()=>!$('#scan-question'));
 assert.equal((await attendance(3)).mass,'unknown');
 const original=await attendance(1);await scan(0);
 assert.match($('#scan-result').textContent,/já registrada/);assert.equal($('#scan-question'),null);
 assert.equal((await attendance(1)).scanned_at,original.scanned_at);
 assert.equal((await attendance(1)).mass,'yes');
 await scan(3);failMass=true;$('[data-action="scan-mass:yes"]').click();
 await until(()=>$('#scan-question .form-error')?.textContent.includes('conexão'));
 assert.equal((await attendance(4)).presence,'present');assert.equal((await attendance(4)).mass,'unknown');
 assert.ok($('#scan-question'));failMass=false;$('[data-action="scan-mass:no"]').click();await until(()=>!$('#scan-question'));
 clock+=4000;
 const manual=await db.get('SELECT student_code FROM students WHERE id=5');
 $('#student-code').value=manual.student_code;
 $('#student-code-form').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:$('#student-code-form button')}));
 await until(()=>$('#scan-question'));
 assert.equal((await attendance(5)).presence,'present');
 $('[data-action="scan-mass:unknown"]').click();await until(()=>!$('#scan-question'));
 assert.equal($('#student-code').value,'');assert.equal($('#student-code-form').hidden,false);
 assert.equal((await attendance(5)).mass,'unknown');
 $('[data-action^="close-call:"]').click();await until(()=>$('#dialog').open&&$('#mass-review'));
 assert.equal($('#mass-review [data-student="1"]'),null);assert.equal($('#mass-review [data-student="2"]'),null);
 assert.ok($('#mass-review [data-student="3"]'));assert.equal($('#mass-review [data-student="4"]'),null);
 $('[data-action="review-mass:yes:3"]').click();await until(()=>!$('#mass-review [data-student="3"]'));
 assert.equal((await attendance(3)).mass,'yes');
 $('[data-action=finish-call]').click();await until(async()=>(await db.get('SELECT status FROM calls WHERE id=?',call.id)).status==='closed');
 await until(()=>$('#toast').textContent==='Chamada encerrada.'&&!$('#video'));
 assert.equal((await attendance(6)).presence,'absent');
 assert.equal((await db.get('SELECT count(*) AS n FROM attendance WHERE call_id=? AND student_id=1',call.id)).n,1);
});
