import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {testApp} from '../test-support/database.js';

test('interface: login, navegação, criação de turma e relatório',async t=>{
 const {server,db}=await testApp(t);
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base=`http://127.0.0.1:${server.address().port}`;
 const dom=new JSDOM(readFileSync(new URL('../public/index.html',import.meta.url),'utf8'),{url:base,runScripts:'outside-only'});
 t.after(()=>dom.window.close());
 const {window:w}=dom;let cookie='';
 w.fetch=async(url,options={})=>{const r=await fetch(base+url,{...options,headers:{...options.headers,Cookie:cookie}});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;};
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.eval(readFileSync(new URL('../public/app.js',import.meta.url),'utf8'));
 async function until(fn){for(let i=0;i<750;i++){if(await fn())return;await new Promise(r=>setTimeout(r,20));}throw new Error('Estado esperado não encontrado: '+w.document.body.textContent.slice(0,700));}
 const find=s=>w.document.querySelector(s);
 await until(()=>find('#login'));
 find('[name=email]').value='professor@demo.local';find('[name=password]').value='Demo@2026!';
 find('#login').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:find('#login button')}));
 await until(()=>find('h1')?.textContent.includes('Olá, Maria'));
 assert.ok(w.document.body.textContent.includes('Novos cadastros'));
 Object.defineProperty(w,'innerWidth',{value:390,writable:true});
 find('[data-action=menu]').click();assert.ok(find('.sidebar').classList.contains('visible'));
 assert.equal(find('[data-action=menu]').getAttribute('aria-expanded'),'true');
 find('.menu-backdrop').click();assert.ok(!find('.sidebar').classList.contains('visible'));
 find('[data-action=menu]').click();find('[data-action=menu]').click();assert.ok(!find('.sidebar').classList.contains('visible'));
 find('[data-action=menu]').click();find('.sidebar a[href="#home"]').click();assert.ok(!find('.sidebar').classList.contains('visible'));
 await new Promise(resolve=>setTimeout(resolve,30));
 find('[data-action=menu]').click();w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));assert.ok(!find('.sidebar').classList.contains('visible'));
 find('[data-action=menu]').click();w.innerWidth=1200;w.dispatchEvent(new w.Event('resize'));assert.ok(!find('.sidebar').classList.contains('visible'));
 assert.equal(find('.menu-backdrop').hidden,true);
 w.location.hash='classes';await until(()=>find('[data-action=new-class]'));
 find('[data-action=new-class]').click();find('#modal-form [name=name]').value='Turma criada pela interface';
 find('#modal-form').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:find('#modal-form button[type=submit]')}));
 await until(()=>w.document.body.textContent.includes('Turma criada pela interface')&&!find('#dialog').open);
 assert.equal((await db.get('SELECT count(*) AS n FROM classes')).n,2);
 w.location.hash='pending';await until(()=>find('#students-list'));
 assert.ok(w.document.body.textContent.includes('João Pedro Alves'));
 find('[data-action="student:8"]').click();find('[data-action="approve:8"]').click();
 await until(async()=>(await db.get('SELECT status FROM students WHERE id=8')).status==='approved'&&!find('#dialog').open);
 w.location.hash='reports';await until(()=>find('#report-output h2'));
 find('#report-month').value='2026-09';find('#report-month').dispatchEvent(new w.Event('change'));
 await until(()=>find('#report-output').textContent.includes('01/09/2026'));
 assert.ok(find('#csv').href.includes('/api/report.csv?'));
 w.location.hash='call';await until(()=>find('#start-call'));
 assert.ok(find('#start-call select').options.length===2);
 w.location.hash='history';await until(()=>find('#history-list table'));
 find('[data-action="call:2"]').click();await until(()=>find('#attendance-list table'));
 assert.equal(w.document.querySelectorAll('.mass-select').length,7);
 w.location.hash='classes';await until(()=>find('.content [data-action="team:1"]'));
 find('.content [data-action="team:1"]').click();await until(()=>find('#team-invite'));
 find('#team-invite [name=email]').value='catequista-ui@example.com';
 find('#team-invite').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:find('#team-invite button[type=submit]')}));
 await until(()=>find('#invite-link')?.value.includes('/#catechist/'));
 const catechistRoute=new URL(find('#invite-link').value).hash;
 find('#dialog [data-action=close]').click();
 find('[data-action=logout]').click();await until(()=>find('#login'));
 find('[name=email]').value='aluno@demo.local';find('[name=password]').value='Demo@2026!';
 find('#login').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:find('#login button')}));
 await until(()=>find('img[alt="Seu QR Code de presença"]'));
 assert.ok(w.document.body.textContent.includes('Meus encontros'));
 assert.equal(find('a[href="#students"]'),null);
 w.location.hash=catechistRoute;
 await until(()=>find('#catechist-register'));
 assert.equal(find('#catechist-register [name=email]').value,'catequista-ui@example.com');
 find('#catechist-register [name=name]').value='Catequista da Interface';
 find('#catechist-register [name=password]').value='SenhaEquipe123!';
 find('#catechist-register [name=confirm]').checked=true;
 find('#catechist-register').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:find('#catechist-register button[type=submit]')}));
 await until(()=>find('.content [data-action="team:1"]'));
 assert.equal((await db.get('SELECT role FROM users WHERE email=?','catequista-ui@example.com')).role,'teacher');
 assert.equal(w.document.querySelectorAll('.content [data-action^="team:"]').length,1);
 find('.content [data-action="team:1"]').click();await until(()=>find('#team-list'));
 assert.ok(find('#team-list').textContent.includes('Catequista da Interface'));
 assert.ok(find('#team-list').textContent.includes('Maria Oliveira'));
 assert.equal(find('#team-invite'),null);
});
