-- Private schema: the browser continues using the Node API and its sessions.
-- Flags remain 0/1 to preserve the existing API and SQLite fallback.
-- The migration runner substitutes only the validated schema identifier for tests.
CREATE SCHEMA presenca;
REVOKE ALL ON SCHEMA presenca FROM PUBLIC, anon, authenticated, service_role;

CREATE TABLE presenca.users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL, email text NOT NULL, password text NOT NULL,
 role text NOT NULL CHECK (role IN ('teacher','student')),
 active smallint NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
 created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX users_email ON presenca.users (lower(email));

CREATE TABLE presenca.classes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL, teacher_id bigint NOT NULL REFERENCES presenca.users(id),
 invite text UNIQUE,
 invite_enabled smallint NOT NULL DEFAULT 1 CHECK (invite_enabled IN (0,1)),
 invite_expires timestamptz,
 open smallint NOT NULL DEFAULT 1 CHECK (open IN (0,1)),
 active smallint NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
 mass_present_only smallint NOT NULL DEFAULT 0 CHECK (mass_present_only IN (0,1)),
 student_history smallint NOT NULL DEFAULT 1 CHECK (student_history IN (0,1)),
 created_at timestamptz NOT NULL
);
CREATE TABLE presenca.students (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint UNIQUE NOT NULL REFERENCES presenca.users(id),
 class_id bigint NOT NULL REFERENCES presenca.classes(id), name text NOT NULL,
 phone text, birth_date date, guardian text, guardian_phone text,
 status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','correction')),
 active smallint NOT NULL DEFAULT 0 CHECK (active IN (0,1)),
 qr_token text UNIQUE, qr_version integer NOT NULL DEFAULT 0 CHECK (qr_version >= 0),
 reason text, terms_at timestamptz NOT NULL, created_at timestamptz NOT NULL,
 approved_at timestamptz, approved_by bigint REFERENCES presenca.users(id)
);
CREATE UNIQUE INDEX students_phone ON presenca.students(phone) WHERE phone IS NOT NULL AND phone <> '';
CREATE TABLE presenca.sessions (
 token_hash text PRIMARY KEY, user_id bigint NOT NULL REFERENCES presenca.users(id),
 csrf text NOT NULL, expires bigint NOT NULL
);
CREATE TABLE presenca.calls (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 class_id bigint NOT NULL REFERENCES presenca.classes(id), date date NOT NULL,
 started_at timestamptz NOT NULL, ended_at timestamptz,
 created_by bigint NOT NULL REFERENCES presenca.users(id),
 status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
 UNIQUE (class_id,date)
);
CREATE TABLE presenca.attendance (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 call_id bigint NOT NULL REFERENCES presenca.calls(id),
 student_id bigint NOT NULL REFERENCES presenca.students(id),
 presence text NOT NULL DEFAULT 'unregistered' CHECK (presence IN ('unregistered','present','absent')),
 scanned_at timestamptz,
 mass text NOT NULL DEFAULT 'unknown' CHECK (mass IN ('yes','no','unknown')),
 updated_at timestamptz, updated_by bigint REFERENCES presenca.users(id),
 UNIQUE (call_id,student_id)
);
CREATE TABLE presenca.corrections (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id bigint NOT NULL REFERENCES presenca.students(id), message text NOT NULL,
 status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','reviewed')),
 created_at timestamptz NOT NULL, reviewed_at timestamptz,
 reviewed_by bigint REFERENCES presenca.users(id)
);
CREATE TABLE presenca.logs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint REFERENCES presenca.users(id), action text NOT NULL,
 entity text NOT NULL, record_id bigint, before_data text, after_data text,
 created_at timestamptz NOT NULL
);

CREATE FUNCTION presenca.validate_attendance() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
BEGIN
 IF NOT EXISTS (
   SELECT 1 FROM presenca.students s JOIN presenca.calls c ON c.id=NEW.call_id
   WHERE s.id=NEW.student_id AND s.status='approved' AND s.active=1 AND s.class_id=c.class_id
 ) THEN
   RAISE EXCEPTION 'Aluno não aprovado, inativo ou de outra turma' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION presenca.validate_attendance() FROM PUBLIC, anon, authenticated, service_role;
CREATE TRIGGER approved_attendance BEFORE INSERT ON presenca.attendance
 FOR EACH ROW EXECUTE FUNCTION presenca.validate_attendance();

CREATE INDEX classes_teacher ON presenca.classes(teacher_id);
CREATE INDEX student_class ON presenca.students(class_id,status);
CREATE INDEX students_approver ON presenca.students(approved_by);
CREATE INDEX sessions_user ON presenca.sessions(user_id);
CREATE INDEX sessions_expiry ON presenca.sessions(expires);
CREATE INDEX call_date ON presenca.calls(date,class_id);
CREATE INDEX calls_creator ON presenca.calls(created_by);
CREATE INDEX attendance_student ON presenca.attendance(student_id,call_id);
CREATE INDEX attendance_updater ON presenca.attendance(updated_by);
CREATE INDEX corrections_student ON presenca.corrections(student_id);
CREATE INDEX corrections_reviewer ON presenca.corrections(reviewed_by);
CREATE INDEX logs_user ON presenca.logs(user_id,id DESC);

-- Only the trusted Node backend role can use these tables. Authorization by
-- teacher/student continues in the API; Supabase JWT identities are not used.
REVOKE ALL ON ALL TABLES IN SCHEMA presenca FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA presenca FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE ON SCHEMA presenca TO presenca_app;
GRANT SELECT, INSERT, UPDATE ON presenca.users, presenca.classes, presenca.students,
 presenca.calls, presenca.attendance, presenca.corrections TO presenca_app;
GRANT SELECT, INSERT, DELETE ON presenca.sessions TO presenca_app;
GRANT SELECT, INSERT ON presenca.logs TO presenca_app;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA presenca TO presenca_app;
GRANT EXECUTE ON FUNCTION presenca.validate_attendance() TO presenca_app;

ALTER TABLE presenca.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenca.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenca.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenca.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenca.calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenca.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenca.corrections ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenca.logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY backend_only ON presenca.users TO presenca_app USING (true) WITH CHECK (true);
CREATE POLICY backend_only ON presenca.classes TO presenca_app USING (true) WITH CHECK (true);
CREATE POLICY backend_only ON presenca.students TO presenca_app USING (true) WITH CHECK (true);
CREATE POLICY backend_only ON presenca.sessions TO presenca_app USING (true) WITH CHECK (true);
CREATE POLICY backend_only ON presenca.calls TO presenca_app USING (true) WITH CHECK (true);
CREATE POLICY backend_only ON presenca.attendance TO presenca_app USING (true) WITH CHECK (true);
CREATE POLICY backend_only ON presenca.corrections TO presenca_app USING (true) WITH CHECK (true);
CREATE POLICY backend_only ON presenca.logs TO presenca_app USING (true) WITH CHECK (true);

CREATE TABLE presenca._migrations (
 version text PRIMARY KEY, checksum text NOT NULL, applied_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE presenca._migrations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON presenca._migrations FROM PUBLIC, anon, authenticated, service_role, presenca_app;
