ALTER TABLE presenca.users ADD COLUMN cpf_hash text;
ALTER TABLE presenca.users ADD COLUMN phone_hash text;
ALTER TABLE presenca.users ADD COLUMN phone_encrypted text;
CREATE UNIQUE INDEX users_cpf_hash ON presenca.users(cpf_hash) WHERE cpf_hash IS NOT NULL;
CREATE UNIQUE INDEX users_phone_hash ON presenca.users(phone_hash) WHERE phone_hash IS NOT NULL;
ALTER TABLE presenca.students ADD COLUMN student_code text;
UPDATE presenca.students SET student_code=upper(substr(replace(gen_random_uuid()::text,'-',''),1,10)) WHERE student_code IS NULL;
CREATE UNIQUE INDEX students_code ON presenca.students(student_code);
CREATE TABLE presenca.password_resets(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES presenca.users(id),token_hash text NOT NULL UNIQUE,
 expires_at bigint NOT NULL,created_at timestamptz NOT NULL,used_at timestamptz
);
CREATE INDEX password_resets_user ON presenca.password_resets(user_id);
CREATE INDEX password_resets_expiry ON presenca.password_resets(expires_at);
ALTER TABLE presenca.password_resets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON presenca.password_resets FROM PUBLIC,anon,authenticated,service_role;
GRANT SELECT,INSERT,UPDATE,DELETE ON presenca.password_resets TO presenca_app;
REVOKE ALL ON SEQUENCE presenca.password_resets_id_seq FROM PUBLIC,anon,authenticated,service_role;
GRANT USAGE ON SEQUENCE presenca.password_resets_id_seq TO presenca_app;
CREATE POLICY backend_only ON presenca.password_resets TO presenca_app USING(true) WITH CHECK(true);
