CREATE TABLE presenca.class_catechists (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 class_id bigint NOT NULL REFERENCES presenca.classes(id),
 user_id bigint NOT NULL REFERENCES presenca.users(id),
 active smallint NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
 added_at timestamptz NOT NULL,
 added_by bigint NOT NULL REFERENCES presenca.users(id),
 UNIQUE(class_id,user_id)
);
CREATE INDEX class_catechists_user ON presenca.class_catechists(user_id,class_id) WHERE active=1;
CREATE INDEX class_catechists_added_by ON presenca.class_catechists(added_by);

CREATE TABLE presenca.catechist_invites (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 class_id bigint NOT NULL REFERENCES presenca.classes(id),
 email text NOT NULL,
 token_hash text NOT NULL UNIQUE,
 expires_at timestamptz NOT NULL,
 created_at timestamptz NOT NULL,
 created_by bigint NOT NULL REFERENCES presenca.users(id),
 accepted_at timestamptz,
 accepted_by bigint REFERENCES presenca.users(id),
 revoked_at timestamptz
);
CREATE INDEX catechist_invites_class ON presenca.catechist_invites(class_id,email);
CREATE INDEX catechist_invites_creator ON presenca.catechist_invites(created_by);
CREATE INDEX catechist_invites_acceptor ON presenca.catechist_invites(accepted_by);

CREATE VIEW presenca.teacher_classes WITH (security_invoker=true) AS
 SELECT id AS class_id,teacher_id AS user_id FROM presenca.classes
 UNION
 SELECT class_id,user_id FROM presenca.class_catechists WHERE active=1;
REVOKE ALL ON presenca.teacher_classes FROM PUBLIC,anon,authenticated,service_role;
GRANT SELECT ON presenca.teacher_classes TO presenca_app;

ALTER TABLE presenca.class_catechists ENABLE ROW LEVEL SECURITY;
ALTER TABLE presenca.catechist_invites ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON presenca.class_catechists,presenca.catechist_invites FROM PUBLIC,anon,authenticated,service_role;
GRANT SELECT,INSERT,UPDATE ON presenca.class_catechists,presenca.catechist_invites TO presenca_app;
REVOKE ALL ON SEQUENCE presenca.class_catechists_id_seq,presenca.catechist_invites_id_seq FROM PUBLIC,anon,authenticated,service_role;
GRANT USAGE ON SEQUENCE presenca.class_catechists_id_seq,presenca.catechist_invites_id_seq TO presenca_app;
CREATE POLICY backend_only ON presenca.class_catechists TO presenca_app USING(true) WITH CHECK(true);
CREATE POLICY backend_only ON presenca.catechist_invites TO presenca_app USING(true) WITH CHECK(true);

ALTER TABLE presenca.logs ADD COLUMN class_id bigint REFERENCES presenca.classes(id);
CREATE INDEX logs_class ON presenca.logs(class_id,id DESC);
UPDATE presenca.logs l SET class_id=CASE
 WHEN entity='classes' THEN (SELECT id FROM presenca.classes WHERE id=l.record_id)
 WHEN entity='students' THEN (SELECT class_id FROM presenca.students WHERE id=l.record_id)
 WHEN entity='calls' THEN (SELECT class_id FROM presenca.calls WHERE id=l.record_id)
 WHEN entity='attendance' THEN (SELECT c.class_id FROM presenca.attendance a JOIN presenca.calls c ON c.id=a.call_id WHERE a.id=l.record_id)
 WHEN entity='corrections' THEN (SELECT s.class_id FROM presenca.corrections r JOIN presenca.students s ON s.id=r.student_id WHERE r.id=l.record_id)
 END;
